name: Build Package

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash -el {0}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: bash

      - name: Build package
        run: |
          rattler-build build --output-dir=./output/ --log-style=plain --color=always --no-include-recipe

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: output/**/*.tar.gz
